### ISSUE TITLE
Hybrid mode?

### ISSUE THREAD

**Issue by btopro** [vpusher/the-grid#21]
Anyone know what would be needed to make this work in hybrid mode (ala work in Polymer 1.x and 2.x)?

https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements

Would love to use this element in my project but having trouble tracing what's involved in getting it to work in 1.x

**Comment by vpusher** [comment]
@btopro If `<the-grid>` is not fully hybrid it should be very close. You should give it a try in your 1.x app et tell me if it needs any improvement/changes.
As an advice, and I don't know how much dependencies you have and how big is your code base, but you should really consider moving your app to Polymer 2.x. It is far more easier to support hybrid component from there than the opposite way.

**Comment by btopro** [comment]
good to know. Yeah I can't figure out why when I try to update to P2.x that it breaks a lot of my stuff; wish there was a "just include everything from P1" mode :)

**Comment by anujparikh** [comment]
@vpusher: Any plans to make this particular component as hybrid component, so that it can be used in our polymer1.x application? When I am trying to use this element in our Polymer1x application it is giving us below mentioned error. 
`Polymer.GestureEventListeners is not a function`
Any types of pointers would be appreciated. TIA

**Comment by DarkSideOfMo0n** [comment]
This Component works great in Hybrid Mode no action needed. What i did was created a Hybrid Component that uses the grid and it just works fine. 
@anujparikh Just upgrade your Polymer App to Hybrid and it will work. The error you get is because you have Polymer 1 as dependency. And Polymer 1 does not provide the GestureEventListeners. Making your Component Hybrid is mostlikely very easy just add Polymer 2 as dependency in your bower.json. Since Polymer 2 also provides the polymer.html file it might just be that or at least that did it for me.

**Comment by vpusher** [comment]
Glad to hear that ! @btopro @anujparikh can we close ? Seems to be solved by importing Polymer 2 as dependency.

**Comment by anujparikh** [comment]
@PascalLaier: Thanks for responding. But I tried the approach which you suggest, but it is not working for me currently. So i have forked the repo and made changes to make pure Polymer1.x  component. But now the component is not getting proper styling. Can you please help me debug the issue. The link to forked repo: https://github.com/anujparikh/the-grid 
I would really appreciate your help.
@vpusher: Your inputs also be appreciated.

**Comment by DarkSideOfMo0n** [comment]
@anujparikh Oh boy there is a lot more wrong than just styles ;-). I will have a look this weekend.

**Comment by anujparikh** [comment]
Thank you so much !! Really appreciate it :)

**Comment by anujparikh** [comment]
@PascalLaier: Where you able to find out anything for forked `the-grid` polymer1x component under my github ?

**Comment by anujparikh** [comment]
@PascalLaier @vpusher: Can you guys help me build a basic grid without draggable and resize. I think only function we need to convert into compatible Polymer1x would be `computeStyles`. If anyone of you can help me out, that would be awesome. TIA !!
